-- Generated by Cursor — kitchen-sink of risky Postgres changes
-- Co-Authored-By: Cursor <noreply@cursor.sh>

-- Rewrite the whole table
ALTER TABLE users ALTER COLUMN created_at TYPE timestamptz;

-- Validates against every existing row under ACCESS EXCLUSIVE
ALTER TABLE users ADD CONSTRAINT users_org_fk FOREIGN KEY (org_id) REFERENCES orgs(id);

-- Builds the unique index inline, blocking writes
ALTER TABLE users ADD CONSTRAINT users_email_uniq UNIQUE (email);

-- Adds a PRIMARY KEY inline (rare but spectacular)
ALTER TABLE audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

-- CHECK constraint without NOT VALID
ALTER TABLE orders ADD CONSTRAINT positive_total CHECK (total >= 0);

-- SET NOT NULL on populated table
ALTER TABLE users ALTER COLUMN email SET NOT NULL;

-- Volatile default that surprises everyone
ALTER TABLE sessions ALTER COLUMN created_at SET DEFAULT now();

-- Destructive truncate hidden in the middle
TRUNCATE TABLE staging_logs CASCADE;

-- Backfill in a single transaction
UPDATE users SET legacy_status = 'archived';

-- Enum rename — silent app break
ALTER TYPE order_status RENAME VALUE 'pending' TO 'awaiting_payment';
